# JAVA_HOME must be set to the JDK installation directory (for example,
# /usr/local/jdk1.3).

all :
	${JAVA_HOME}/bin/javac \
    -sourcepath ../../../src \
    -classpath ../../../classes:../../../lib/charva.jar \
    -d ../../../classes \
    *.java

